#spring.application.name=onTime
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = ${DB_URL}
#spring.datasource.username = ${DB_USERNAME}
#spring.datasource.password =${DB_PASSWORD}
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.security.user.name=sri
#spring.security.user.password=sri@2006
#spring.security.user.roles=ADMIN,USER
#server.servlet.session.cookie.secure=${COOKIE_SECURE:false}
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.same-site=${COOKIE_SAME_SITE:Lax}
#spring.session.cookie.name=JSESSIONID
#spring.jackson.date-format=yyyy-MM-dd'T'HH:mm
#spring.jackson.serialization.write-dates-as-timestamps=false
spring.application.name=onTime

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.security.user.name=sri
spring.security.user.password=sri@2006
spring.security.user.roles=ADMIN,USER

server.servlet.session.cookie.secure=${COOKIE_SECURE:false}
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=${COOKIE_SAME_SITE:Lax}

spring.session.cookie.name=JSESSIONID

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=${PORT:8080}